### ISSUE TITLE
Variable name shadows built-in string library

### ISSUE THREAD

**Issue by mikelane** [NARCOTIC/PY-NOOB#2]
The use of the variable name `string` [here](https://github.com/NARCOTIC/PY-NOOB/blob/4fa0434f4f857300186ab938f1a7139716b62a34/Lesson-002.py#L7) will shadow the built-in string library. You should avoid this if possible.

**Comment by NARCOTIC** [comment]
Fixed [Issue #2](https://github.com/NARCOTIC/PY-NOOB/commit/64412b5fa6975b083edfb8ab26e8ec2d4019aa5a#diff-c9f283ea72a065eab08dfacd15cfd2c8). Thanks for reporting.
